### ISSUE TITLE
Report benchmarks websockets incorrectly and misrepresents it

### ISSUE THREAD

**Issue by aaugustin** [matttomasetti/Python-Websockets_Websocket-Benchmark-Server#1]
Hello, I'm the primary author of websockets. Thanks for your interest in benchmarking it.

The defaults are geared towards general use, not micro benchmarks. This explains the results that you got without tuning.

However, I take issue with factually incorrect statements that you included in your paper:

> For  the  Python 
> websocket,  a  generic  module  is  used  which  is  simply  named 
> "websockets".  The  documentation  for  this  module  is  limited

websockets has extensive documentation: https://websockets.readthedocs.io/en/stable/
 
> and  custom  configuration  is non-existent.

There's about a dozen configuration knobs: https://websockets.readthedocs.io/en/stable/reference/server.html#websockets.server.serve

> This  is  most  likely  a 
> module that offers the simplest of websocket functionality. 

websockets is among the most feature complete WebSocket implementations. This is also why it tends to perform poorly in micro-benchmarks: if you benchmark a library that implements compression and enables it by default, requiring ~100kb of memory per connection to hold compression buffers, against a library that doesn't, obviously the first library loses.

To compare apples-to-apples, probably you need to disable compression, keepalive, and possibly UTF-8 decoding.

It would be polite to reach out to authors before publishing disparaging and false statements.

**Comment by matttomasetti** [comment]
Hey @aaugustin,
Let me start off by saying thank you for your contributions to the development community, as well as for taking the time to peer review my research and supply feedback. It is truly much appreciated.  

Let me also recap the purpose of my research. I performed my testing for my own personal knowledge gain on various WebSocket implementations and wrote a formal write-up to assist others who may have the same questions I was asking. My goal was to find the implementation that offered the best performance with minimal configuration, to align best with a desire for rapid development. Therefore ALL implementations were set up in such a manner. I am confident that the Python websockets implementation, as well as ALL other implementations, would have benefited from additional "tuning" as I stated in my paper, and as you have mentioned in your post. However, finely tuning each variation was not the goal, as I wanted to know the "out of the box" performance if you will. This is because, for use in my projects, WebSockets are a single component in a much larger application, and therefore I want to be able to focus my time on building out the software as a whole and not fixating solely on tuning the WebSocket.  

As far as reaching out to the author of each package and module used, that hardly seems like something that would occur in a real-world situation. I may be speaking anecdotally, but if I found a module that didn't meet my needs while developing for work or a personal project, I would not reach out to the creator of the module. Rather, I would simply just find another module that does meet my needs.  

My findings have been more helpful than I could have hoped. And I can confidently say that the results are neither disparaging nor contain false statements, as they are easily reproducible and backed by data. I'm not claiming that my testing was flawless, however, to solo a follow-up project of this caliber would consume more time than I can allocate right now.

Another developer, @villekr had reached out to me about the result for the Python WebSocket and took it upon himself to develop some benchmarks of his own. Perhaps you would enjoy his more Pyhton-centric results found here: [Python is slow… Wait, it’s actually fast!](https://ville-karkkainen.medium.com/python-is-slow-wait-its-actually-fast-6d2e49621b1)  

Thank you again for reaching out, I hope this can shed some light on the purpose of my testing. Also, please let me know if you do any benchmarking of your own or any other kind of research. I would be thrilled to read it. Or, feel free to reach out if you ever have any interest in teaming up on a project.
